### ISSUE TITLE
Hide FileConfiguration and OutputCache controller from Swagger

### ISSUE THREAD

**Issue by Marusyk** [ThreeMammals/Ocelot#989]
## Expected Behavior / New Feature
I do not need to display FileConfigurationController and OutputCacheController in my swagger of API Geteway.

## Actual Behavior / Motivation for New Feature
![Screenshot_1](https://user-images.githubusercontent.com/9221694/62981007-d1424680-be30-11e9-8897-c016b83e1273.png)

## Steps to Reproduce the Problem

  1. Install-Package Ocelot -Version 13.5.2

How to hide/remove them?

**Comment by darcon77** [comment]
Implement custom API Explorer like so:
```csharp
public class FilteredApiExplorer : IApiExplorer
{
    public Collection<ApiDescription> ApiDescriptions { get; }

    public FilteredApiExplorer(IApiExplorer explorer)
    {
        ApiDescriptions = new Collection<ApiDescription>(explorer.ApiDescriptions
            .Where(d => !d.ActionDescriptor.ControllerDescriptor.ControllerType.FullName.Contains("FileConfigurationController"))
            .ToList());
    }
}
```

Then replace the instance of IApiExplorer class in DI container with the custom one: `Services.Replace(typeof(IApiExplorer), new FilteredApiExplorer(apiExplorer));`

**Comment by Marusyk** [comment]
Thanks @darcon77,
I know how to do it in swagger, but I hope that there are some setting in Ocelot for this.

For now I've solved it in this way

```csharp
internal class HideOcelotControllersFilter : IDocumentFilter
{
    private static readonly string[] _ignoredPaths = {
        "/configuration",
        "/outputcache/{region}"
    };

    public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
    {
        foreach(var ignorePath in _ignoredPaths)
        {
            swaggerDoc.Paths.Remove(ignorePath);
        }
    }
}
```
then
```csharp 
services.AddSwaggerGen(cfg =>
{
    cfg.DocumentFilter<HideOcelotControllersFilter>();
});
```
it's tricky, I'm looking for another way

**Comment by joaopgrassi** [comment]
I think this shouldn't be closed. Both solutions above work but are not ideal. In essence, unless necessary I think Ocelot should hide these controllers from being "discovered" by things like Swashbuckle. 

I didn't have time to look into the code, but just adding `[ApiExplorerSettings(IgnoreApi=true)]` should do the job.

**Comment by raman-m** [comment]
The issue has been [accepted](#event-10211759901) due to opened PR #1532 
- #1532

**Comment by raman-m** [comment]
Should be fixed as a part of ##1429

**Comment by pmandalka** [comment]
As https://github.com/ThreeMammals/Ocelot/pull/1429 is still not closed, here a simple solution to not only remove the Endpoints, but also the data-models from the OpenAPI definition. Add a DocInclusionPredicate to your "AddSwaggerGen"-Method - see below. This will remove all Actions that are defined in the Ocelot.Administartion-Namespace from the OpenAPI.


```CSharp

services.AddSwaggerGen(c =>
 {
     
     c.DocInclusionPredicate((documentId, apiDescription) =>
     {
         if (apiDescription.ActionDescriptor.DisplayName?.StartsWith("Ocelot.Administration.") ?? false)
         {
             return false;
         }
         return true;
     });
 /// your code...

```

**Comment by raman-m** [comment]
> @pmandalka wrote [on April 24](https://github.com/ThreeMammals/Ocelot/issues/989#issuecomment-4314228866)

Thanks! That's a useful life hack to hide system endpoints when the user doesn't utilize the [Administration](https://ocelot.readthedocs.io/en/latest/features/administration.html) feature. 😄 
Currently, the [Administration](https://ocelot.readthedocs.io/en/latest/features/administration.html) feature is under review due to its outdated design based on controllers. There's a high chance those controllers will be removed in favor of system Ocelot routes.

**Comment by raman-m** [comment]
@Burgyn Hi, Miňo!
Does your lib have something to do with those Ocelot system controllers to hide them?

What would you recommend?
1. Our team will fix this bug officially.
2. Your [MMLib.SwaggerForOcelot](https://github.com/Burgyn/MMLib.SwaggerForOcelot) project has something built-in.
